---
# simplespeedtest.yml
- hosts: compute
  gather_facts: no
  vars:
    var1: 1
    var2: 2
  tasks:
    - debug: msg={{inventory_hostname}}
      delegate_to: localhost
    - debug: msg=task1
    - debug: msg=task2
    - debug: msg={{item}}
      with_sequence: start=1 end=5
    - debug: msg={{item}}
      no_log: yes
      with_items: [ "{{var1}}", "{{var2}}" ]
      delegate_to: localhost
